<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>vDosPrintMonitor</AssemblyName>
    <RootNamespace>vDosPrintMonitor</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
    <RuntimeIdentifiers>win-x86</RuntimeIdentifiers>
  </PropertyGroup>

</Project>
